Add support for filtering report issues by severity/confidence/paths
vmware/burp-rest-api pull request #129
Opened 2022-02-01 21:03 UTC by zam0x1ma

@ikkisoft This adds the Severity, Confidence and Path filters in the `/burp/report` endpoint, as suggested in #125

2022-02-02 12:47 UTC, ikkisoft requested changes
Besides the minor comment I made around paths and URL, i believe this is ready to be merged. 

Another improvement could be to write (or expand) the scan & report test in https://github.com/vmware/burp-rest-api/blob/master/src/test/java/com/vmware/burp/extension/client/BurpClientIT.java

2022-02-02 12:47 UTC, ikkisoft commented on src/main/java/com/vmware/burp/extension/service/BurpService.java
> +        Supplier<Stream<IScanIssue>> scanIssuesSupplier = () -> Arrays.stream(burpExtenderCallbacks.getScanIssues(urlPrefix));
I am not sure it makes sense to have _urlPrefix_ as well as _issuePath_

_urlPrefix_  is actually a URL so in the form http(s)://doyensec.com/
_issuePath_ are just URI paths

We can leave as is, but I would adjust the description in the `ApiImplicitParam` to specify that for users

2022-02-02 12:47 UTC, ikkisoft commented on src/main/java/com/vmware/burp/extension/service/BurpService.java
> +        IScanIssue[] filteredScanIssues = scanIssuesSupplier.get()
Very clean way of filtering issues

2022-02-02 22:06 UTC, ikkisoft commented
@zam0x1ma Code changes seem ok, but it's not breaking 

`com.vmware.burp.extension.client.BurpClientIT > testScannerSpiderAndReportMethods FAILED`

2022-02-02 22:25 UTC, zam0x1ma commented
@ikkisoft I'm still working in the report test but I'm having issues to run the tests.
Even without my changes they all fail because Spring is not able to find Burp API classes.
Do you happen to know how to workaround this?

2022-02-03 00:51 UTC, zam0x1ma commented
@ikkisoft Nevermind, I was able to run all the tests and fix the one failing.

2022-02-03 21:11 UTC, ikkisoft commented
Reviewed all changes, and performed additional testing. All seems to be working great. Thanks @zam0x1ma for you contribution! Well done!

2022-02-03 21:11 UTC, merged